language: node_js
node_js:
  - "10"

services:
  - mongodb
  - docker

cache:
  directories:
    - server/node_modules

before_install:
  - npm install -g npm
  - npm install -g ganache-cli@~6.1.8
  - cd server

before_script:
  - ganache-cli --port 18545 > ganache-cli.log &
  - git clone https://github.com/oceanprotocol/barge
  - cd barge
  - export KEEPER_VERSION=v0.6.12
  - export BRIZO_VERSION=v0.2.0
  - export AQUARIUS_VERSION=v0.1.8
  - bash -x start_ocean.sh --latest --no-brizo --no-pleuston --local-spree-node 2>&1 > start_ocean.log &
  - cd ..
  - npm run start > server.log &

script:
  - export ETH_PORT=18545
  - npm test

notifications:
  email: false


