version: '2.1'
services:

  mongodb:
    container_name: mongodb
    image: mongo:3.6
    ports:
      - "27017:27017"

  faucet-server:
    container_name: faucet-server
    build: ./server
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      MONGODB_URL: "mongodb://mongodb:27017/faucetdb"
      FAUCET_TOKENS: 10
      FAUCET_TIMESPAN: 24
      KEEPER_URI: "http://keeper-node:8545"
      AQUARIUS_URI: "http://aquarius:5000"
      BRIZO_URI: "http://brizo:8030"
      PARITY_URI: "http://keeper-node:8545"
      SECRETSTORE_URI: "http://secret-store-cors-proxy:12001"
      SECRETSTORE_THRESHOLD: 0
      ACCOUNT_PWD: "node0"
      ADDRESS: "0x00bd138abd70e2f00903268f3db08f2d25677c9e"
    depends_on:
      - mongodb

networks:
  default:
    external:
      name: ocean_backend
