#!/bin/sh
SERVER_PORT=${SERVER_PORT:-3001}
MONGO_URL=${MONGO_URL:-mongodb://localhost:27017/faucetdb}
NODE_SCHEME=${NODE_SCHEME:-http}
NODE_HOST=${NODE_HOST:-localhost}
NODE_PORT=${NODE_PORT:-8545}
AQUARIUS_SCHEME=${AQUARIUS_SCHEME:-http}
AQUARIUS_HOST=${AQUARIUS_HOST:-localhost}
AQUARIUS_PORT=${AQUARIUS_PORT:-5000}
BRIZO_SCHEME=${BRIZO_SCHEME:-http}
BRIZO_HOST=${BRIZO_HOST:-localhost}
BRIZO_PORT=${BRIZO_PORT:-8030}
PARITY_SCHEME=${PARITY_SCHEME:-http}
PARITY_HOST=${PARITY_HOST:-localhost}
PARITY_PORT=${PARITY_PORT:-8545}
SECRET_STORE_SCHEME=${SECRET_STORE_SCHEME:-http}
SECRET_STORE_HOST=${SECRET_STORE_HOST:-localhost}
SECRET_STORE_PORT=${SECRET_STORE_PORT:-12001}
SECRET_STORE_THRESHOLD=${SECRET_STORE_THRESHOLD:-0}
SECRET_STORE_PASSWORD=${SECRET_STORE_PASSWORD:-node0}
SECRET_STORE_ADDRESS=${SECRET_STORE_ADDRESS:-0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e}

envsubst < /server/config/index.js.template > /server/config/index.js

echo "Starting Faucet..."
npm run start
